version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:12.6.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: | 
          npm install # Install dependencies
          npm test # Run Test
